insert into public.product_categories (slug, name, href, group_name, sort) values
('adhesives-sealants', 'Adhesives & Sealants', '/equipment-options/adhesives-sealants', 'Adhesives & Sealants', 0),
('single-component', 'Single Component', '/equipment-options/adhesives-sealants/single-component', 'Adhesives & Sealants', 1),
('two-component', 'Two Component Systems (2k)', '/equipment-options/adhesives-sealants/two-component', 'Adhesives & Sealants', 2),
('putty-paste', 'Putty & Paste', '/equipment-options/adhesives-sealants/putty-paste', 'Adhesives & Sealants', 3),
('smc-imc-molding', 'SMC / IMC Molding', '/equipment-options/adhesives-sealants/smc-imc-molding', 'Adhesives & Sealants', 4),
('tooling-paste', 'Tooling Paste & Seamless Modeling Paste', '/equipment-options/adhesives-sealants/tooling-paste-seamless-modeling-paste', 'Adhesives & Sealants', 5),
('composites', 'Composites', '/equipment-options/composites', 'Composites', 6),
('closed-mold-technology', 'Closed Mold Technology', '/equipment-options/composites/closed-mold-technology', 'Composites', 7),
('filament-winding', 'Filament Winding', '/equipment-options/composites/filament-winding', 'Composites', 8),
('open-mold-technology', 'Open Mold Technology', '/equipment-options/composites/open-mold-technology', 'Composites', 9),
('pull-winding', 'Pull Winding', '/equipment-options/composites/pull-winding', 'Composites', 10),
('lubrication', 'Lubrication', '/equipment-options/lubrication', 'Lubrication', 11),
('metering', 'Metering', '/equipment-options/lubrication/metering', 'Lubrication', 12),
('pressure-control', 'Pressure Control', '/equipment-options/lubrication/pressure-control', 'Lubrication', 13),
('flow-regulation', 'Flow Regulation', '/equipment-options/lubrication/flow-regulation', 'Lubrication', 14),
('dispensing', 'Dispensing', '/equipment-options/lubrication/dispensing', 'Lubrication', 15),
('feeding-and-supply', 'Feeding and Supply', '/equipment-options/lubrication/feeding-and-supply', 'Lubrication', 16),
('paint-coatings', 'Paint & Coatings', '/equipment-options/paint-coatings', 'Paint & Coatings', 17),
('protective-coatings', 'Protective Coatings', '/equipment-options/paint-coatings/protective-coatings', 'Paint & Coatings', 18),
('spray-systems', 'Spray Systems', '/equipment-options/paint-coatings/spray-systems', 'Paint & Coatings', 19),
('process-control', 'Process Control', '/equipment-options/process-control', 'Process Control', 20),
('integration-automation', 'Integration / Automation', '/equipment-options/process-control/integration-automation', 'Process Control', 21),
('monitoring-analytics', 'Monitoring / Analytics', '/equipment-options/process-control/monitoring-analytics', 'Process Control', 22),
('process-control-computer', 'Process Control Computer', '/equipment-options/process-control/process-control-computer', 'Process Control', 23),
('polyurethane', 'Polyurethane', '/equipment-options/polyurethane-processing-equipment', 'Polyurethane', 24),
('bulk-chemical-storage', 'Bulk Chemical Storage', '/bulk-chemical-storage', 'Polyurethane', 25),
('high-pressure-metering', 'High Pressure Metering', '/equipment-options/polyurethane-processing-equipment/high-pressure-metering', 'Polyurethane', 26),
('low-pressure-metering', 'Low Pressure Metering', '/equipment-options/polyurethane-processing-equipment/low-pressure-metering', 'Polyurethane', 27),
('pentane-capable-metering-machines', 'Pentane Capable Metering Machines', '/equipment-options/polyurethane-processing-equipment/pentane-capable-metering-machines', 'Polyurethane', 28),
('urethane-foam-mixing-guns', 'Urethane Foam Mixing Guns', '/equipment-options/polyurethane-processing-equipment/urethane-foam-mixing-guns', 'Polyurethane', 29);